version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: avicola_postgres
    restart: always
    environment:
      POSTGRES_USER: avicola_user
      POSTGRES_PASSWORD: avicola_password
      POSTGRES_DB: avicola_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: